name: unit tests

on:
  push:
    branches: 
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v2

      # Install .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      # Perform unit tests
      - name: Perform unit tests
        run: dotnet test DictionaryStringObjectJsonConverter.Test -l "console;verbosity=normal" -v:q --nologo
